runner:
  textlint:
    cmd: npx textlint -c config/.textlintrc -f checkstyle 'articles/**.md'
    format: checkstyle
  markdownlint:
    cmd: npx markdownlint-cli2 'articles/**.md'
    errorformat:
      - "%f:%l:%c %m"
      - "%f:%l %m"
