version: 1
rules:
  - expected: GitHub
    pattern:
      - Github
      - github
  - expected: Go
    pattern:
      - golang
      - Golang
      - GoLang
  - expected: Google Cloud
    pattern:
      - GCP
      - gcp
